version: "3"

services:
    fictional_parakeet_client:
        build: .
        container_name: fictional_parakeet_client
        ports:
            - "3001:3000"
        volumes:
            - .:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        env_file:
            .env.development.local
